export interface Project {
  id: string;
  type: "hosted" | "local";
  title: string;
  description: string;
  techStack: string[];
  repoUrl: string;
  liveUrl?: string;
  image: string; // URL or local path
  icon: string; // Fallback icon
  isPrivate?: boolean;
  stars?: number;
  role?: string;
  localInstructions?: string[];
}

export const projects: Project[] = [
  {
    id: "river-range-resort",
    type: "hosted",
    isPrivate: true,
    title: "River Range Resort Guest Portal",
    role: "Lead Developer & System Administrator",
    description: "Luxury full-stack portal fusing a cinematic GSAP/Framer UI with an enterprise-grade booking engine. Orchestrates real-time inventory sync and secure DFCC Bank IPG settlements, featuring a proprietary AI concierge and custom geolocation engines.",
    techStack: ["React.js", "Firebase", "DFCC IPG", "GSAP", "Google Maps"],
    repoUrl: "https://github.com/Chanii2024/river-range-resort",
    liveUrl: "https://riverrangehotel.com/",
    image: "/projects/River Range Right View Capture.png",
    icon: "Hotel",
  },
  {
    id: "river-range-erp",
    type: "hosted",
    isPrivate: true,
    title: "River Range Resort Staff ERP",
    role: "Lead Developer & System Administrator",
    description: "Military-grade resort orchestration engine built on a 'Zero Trust' Mesh VPN architecture. Centralizes mission-critical financial controls for DFCC transactions, automated reservation lifecycle verification, and a custom CMS for total operational autonomy.",
    techStack: ["Node.js", "Express", "React.js", "MySQL", "Mesh VPN Security"],
    repoUrl: "#",
    liveUrl: "https://river-range-resort.web.app",
    image: "/projects/river-range-erp.jpg",
    icon: "Lock",
  },
  {
    id: "v-frame",
    type: "local",
    title: "V-Frame: High-Performance Video Engine",
    description: "Multi-threaded Node.js & FFmpeg engine designed for extracting high-quality image sequences from video. Features real-time progress tracking via Server-Sent Events (SSE).",
    techStack: ["Node.js", "FFmpeg", "SSE", "WebP Optimization"],
    repoUrl: "https://github.com/Chanii2024/v-frame",
    image: "/projects/v-frame.jpg",
    icon: "Monitor",
  },
  {
    id: "sonic-pulse",
    type: "local",
    title: "Sonic Pulse: Audio Extraction Hub",
    description: "Full-stack media processing app with a containerized Node.js backend. Features a real-time Web Audio API frequency visualizer and studio-quality MP3 conversion.",
    techStack: ["React", "Docker", "FFmpeg", "Web Audio API"],
    repoUrl: "https://github.com/Chanii2024/sonic-pulse",
    image: "/projects/sonic-pulse.jpg",
    icon: "Music",
  },
  {
    id: "neuralscale",
    type: "local",
    title: "NeuralScale: Browser-Native AI Upscaling",
    description: "High-performance image upscaling using local neural engines. Leverages WebGPU and ONNX Runtime Web for 100% private, on-device AI enhancements.",
    techStack: ["ONNX Runtime", "WebGPU", "Next.js 15", "WASM"],
    repoUrl: "https://github.com/Chanii2024/neural-scale",
    liveUrl: "#",
    image: "/projects/neuralscale.jpg",
    icon: "Cpu",
  },
  {
    id: "cutout-ai",
    type: "local",
    title: "CutOut AI: Background Detection",
    description: "Real-time image processing tool using Vision Transformers (ViT) for professional-grade background removal and object detection classification.",
    techStack: ["FastAPI", "Python", "Vision Transformers", "Next.js"],
    repoUrl: "https://github.com/Chanii2024/cutout-ai",
    liveUrl: "#",
    image: "/projects/cutout-ai.jpg",
    icon: "Layout",
  },
  {
    id: "tasktrace-premium",
    type: "hosted",
    title: "TaskTrace Premium",
    description: "Advanced Jira-style platform for real-time team collaboration, featuring dynamic analytics, sprint tracking, and a glassmorphic design system.",
    techStack: ["Vanilla JS", "Firebase DB", "Chart.js", "Tailwind CSS"],
    repoUrl: "https://github.com/Chanii2024/tasktrace-premium",
    liveUrl: "https://tasktrace-todo.web.app/",
    image: "/projects/tasktrace.jpg",
    icon: "Box",
  },
  {
    id: "studio-ai",
    type: "hosted",
    title: "Studio AI: Batch Processor",
    description: "Privacy-focused batch image processor running entirely on-device via WebAssembly. Engineered for mass renaming, resizing, and format conversion.",
    techStack: ["WASM", "JSZip", "WebAssembly", "Tailwind CSS 4"],
    repoUrl: "https://github.com/Chanii2024/studio-ai",
    liveUrl: "https://chanii2024.github.io/studio-ai/",
    image: "/projects/studio-ai.jpg",
    icon: "Palette",
  },
  {
    id: "orderby",
    type: "hosted",
    title: "OrderBy: Client-Side Org Engine",
    description: "High-performance utility for bulk image renaming and structural organization using local browser resources for privacy-first, serverless processing.",
    techStack: ["HTML5 Canvas", "JSZip", "FileSaver.js", "Framer Motion"],
    repoUrl: "https://github.com/Chanii2024/orderby",
    liveUrl: "https://orderby-uploads.web.app/",
    image: "/projects/orderby.jpg",
    icon: "Layers",
  },
  {
    id: "draftpoint",
    type: "hosted",
    title: "DraftPoint: Client Onboarding Hub",
    description: "Interactive project requirement gathering workflow with dynamic lead generation and automated WhatsApp consultation drafting.",
    techStack: ["React", "Vercel Functions", "Nodemailer", "Framer Motion"],
    repoUrl: "https://github.com/Chanii2024/draftpoint",
    liveUrl: "https://draft-point.vercel.app/",
    image: "/projects/draftpoint.jpg",
    icon: "Smartphone",
  },
  {
    id: "auralia",
    type: "local",
    title: "Auralia Streaming App",
    description: "Java-based media streaming platform (Spotify-style architecture) integrating audio/video playback and personalized recommendations.",
    techStack: ["Java", "Maven", "Tomcat", "MySQL"],
    repoUrl: "https://github.com/Chanii2024/auralia-streaming",
    image: "/projects/auralia.jpg",
    icon: "Music",
  },
  {
    id: "librisense",
    type: "local",
    title: "LibriSense IoT",
    description: "Smart library management system using MQTT and ESP32 sensors to track seating occupancy and book usage in real-time.",
    techStack: ["IoT", "ESP32", "MQTT", "Node.js", "Dashboard"],
    repoUrl: "https://github.com/Chanii2024/librisense-iot",
    liveUrl: "#",
    image: "/projects/iot.world",
    icon: "Box",
  },
  {
    id: "chan-tm",
    type: "hosted",
    isPrivate: false,
    title: "CHAN TM | Pure Acoustic Engineering",
    role: "Lead Developer",
    description: "High-fidelity acoustic engineering landing page. Leverages Next.js 15 and scroll-bound Framer Motion triggers to showcase professional 24-bit/96kHz audio equipment with cinematic precision.",
    techStack: ["Next.js 15", "Framer Motion", "Audio Engine", "React.js"],
    repoUrl: "https://github.com/Chanii2024/chan-tm-acoustic",
    liveUrl: "https://chantm.web.app",
    image: "/projects/repo-chan-tm.jpg",
    icon: "Coffee",
  },
  {
    id: "caresync-clinic",
    type: "local",
    isPrivate: false,
    title: "CareSync Clinic: Elite Healthcare",
    role: "Full Stack Developer",
    description: "Full-scale healthcare management prototype. Engineered for surgical patient coordination and secure clinical data handling, featuring a responsive, high-fidelity UI for modern medical practices.",
    techStack: ["React.js", "Firebase", "Health-Tech", "Lucide"],
    repoUrl: "https://github.com/Chanii2024/caresync-clinic",
    liveUrl: "#",
    image: "/projects/repo-caresync.jpg",
    icon: "Shield",
  },
  {
    id: "turbo-compress",
    type: "hosted",
    isPrivate: false,
    title: "Turbo Compress: Asset Optimization",
    role: "Core Engineer",
    description: "Privacy-focused high-speed compression utility. Utilizes advanced client-side processing to deliver lightning-fast asset optimization without sacrificing data integrity.",
    techStack: ["WASM", "JavaScript", "Asset Pipeline"],
    repoUrl: "https://github.com/Chanii2024/turbo-compress",
    liveUrl: "https://chanii2024.github.io/turbo-compress/",
    image: "/projects/repo-turbo.jpg",
    icon: "Cpu",
  },
  {
    id: "visiongate-optom",
    type: "local",
    isPrivate: false,
    title: "VisionGate Optometrist",
    role: "Lead Developer",
    description: "Sophisticated clinical management engine for optometry practices. Engineered for precise patient data handling, prescription record management, and surgical workflow orchestration.",
    techStack: ["C#", ".NET", "SQL Server", "Clinical UI"],
    repoUrl: "https://github.com/Chanii2024/VisionGateOptometrist",
    liveUrl: "#",
    image: "/projects/repo-visiongate.jpg",
    icon: "Eye",
  },
  {
    id: "mingxing-backend",
    type: "local",
    isPrivate: false,
    title: "Mingxing Backend Architecture",
    role: "System Architect",
    description: "High-concurrency enterprise backend architecture. Engineered for low-latency data orchestration and secure API management for large-scale digital systems.",
    techStack: ["Node.js", "Express", "PostgreSQL", "API Security"],
    repoUrl: "https://github.com/Chanii2024/Mingxing-Backend",
    liveUrl: "https://mingxing-10d5f.web.app/",
    image: "/projects/repo-mingxing.jpg",
    icon: "Server",
  },
  {
    id: "la-cherie-bakery",
    type: "hosted",
    isPrivate: false,
    title: "La Chérie Bakery: Artisanal Hub",
    role: "Lead Developer",
    description: "Elite-tier artisanal bakery platform. Engineered for seamless digital storytelling and gourmet reservation management with a high-fidelity, responsive UI.",
    techStack: ["Next.js", "Tailwind CSS", "Framer Motion", "CMS"],
    repoUrl: "https://github.com/Chanii2024/la-cherie-bakery",
    liveUrl: "https://la-cherie-bakery.web.app/",
    image: "/projects/repo-bakery.jpg",
    icon: "Coffee",
  },
  {
    id: "fleva-platform",
    type: "hosted",
    isPrivate: false,
    title: "Fleva Platform Website",
    role: "Lead Developer",
    description: "Masterpiece of digital commerce. A high-performance platform architecture designed for seamless brand storytelling and elite-level user engagement.",
    techStack: ["React", "Next.js", "Framer Motion", "E-commerce"],
    repoUrl: "https://github.com/Chanii2024/fleva-platform",
    liveUrl: "https://fleva-platform.web.app",
    image: "/projects/repo-fleva.jpg",
    icon: "ShoppingBag",
  },
  {
    id: "mi-coursework",
    type: "local",
    isPrivate: false,
    title: "MI Engine: Fetal Health ML",
    role: "ML Engineer",
    description: "Sophisticated Machine Learning engine specialized in Fetal Health Classification. Orchestrates complex predictive models to deliver high-accuracy clinical insights.",
    techStack: ["Python", "Jupyter", "Scikit-Learn", "Data Science"],
    repoUrl: "https://github.com/Chanii2024/MI-Coursework",
    liveUrl: "#",
    image: "/projects/repo-mi.jpg",
    icon: "Brain",
  },
  {
    id: "auralia-movie-rec",
    type: "local",
    isPrivate: false,
    title: "Auralia Movie Recommendation",
    role: "ML Developer",
    description: "Intelligent recommendation engine for the Auralia ecosystem. Leverages deep learning algorithms to orchestrate personalized high-fidelity media trajectories.",
    techStack: ["JavaScript", "TensorFlow.js", "Data Filtering"],
    repoUrl: "https://github.com/Chanii2024/auralia-movie-recommendation",
    liveUrl: "#",
    image: "/projects/repo-auralia-rec.jpg",
    icon: "Film",
  },
  {
    id: "auralia-user-service",
    type: "local",
    isPrivate: false,
    title: "Auralia User Service",
    role: "Backend Engineer",
    description: "Mission-critical user orchestration service for the Auralia platform. Built on a secure, high-concurrency architecture to manage global authentication and identity lifecycle.",
    techStack: ["Java", "Spring Boot", "Auth0", "Microservices"],
    repoUrl: "https://github.com/Chanii2024/Auralia-User-Service",
    liveUrl: "#",
    image: "/projects/repo-auralia-user.jpg",
    icon: "Users",
  },
  {
    id: "urbanfood-frontend",
    type: "local",
    isPrivate: false,
    title: "Urbanfood Frontend",
    role: "UI/UX Developer",
    description: "Elite-tier food orchestration interface. Designed for high-speed user journeys and professional-grade culinary storytelling with a mobile-responsive UI.",
    techStack: ["React", "Tailwind CSS", "UX Design"],
    repoUrl: "https://github.com/Chanii2024/Urbanfood-Frontend",
    liveUrl: "#",
    image: "/projects/repo-urbanfood.jpg",
    icon: "Utensils",
  },
  {
    id: "tuition-mgmt",
    type: "local",
    isPrivate: false,
    title: "Tuition Management App",
    role: "Full Stack Developer",
    description: "Sophisticated educational management system. Engineered to centralize high-fidelity academic tracking, financial settlement orchestration, and student lifecycle management.",
    techStack: ["Java", "Maven", "MySQL", "Desktop UI"],
    repoUrl: "https://github.com/Chanii2024/TuitionManagementApp",
    liveUrl: "#",
    image: "/projects/repo-tuition.jpg",
    icon: "GraduationCap",
  }
];
